### PR TITLE
Added config option to CLI

### LINKED ISSUE #165: Add config path argument
Would be a nice added CLI option to be able to manually specify the path to your `webextension-toolbox.config.js`. Since that's a bit of a mouthful it would be handy if I could rename it to something like `webext.config.js` or similar and be able to pass something like `--config` or `-c` to specify a config path 😄

### PR DESCRIPTION
**Pull request by NuroDev**
Closes #165 😄 🎉

### CODE REVIEW

**Comment by balcsida** [comment]
Hi @NuroDev,

Again, thank you so much for contributing to this project.
Could you please add some smoke tests to this functionality?
Just an extra config file added to the example extension + an extra command to the test would be enough now.

Kind regards,
@balcsida

**Comment by NuroDev** [comment]
Hey @balcsida 
Added the extra config to the example extension. As for the extra test command, would you prefer it as an entirely separate test command to the current one or added on top of the current test command? (Current one seems very verbose already).
If you would prefer it as a separate command, would you also like me to add the new test command to the Azure pipeline config 😄

**Comment by balcsida** [comment]
Hey @NuroDev,

Thank you for going for the extra mile and my apologies for not doing this myself.

Kind regards,
@balcsida

**Comment by NuroDev** [comment]
Okay, added an example config to the example extension and split the test command into a separate command and added the 2nd test command to the azure CI config.

Everything should be good to merge whenever 😄

**Pull request merged**
