### PR TITLE
Mv3 support

### PR DESCRIPTION
**Pull request by here-nerd**
#196
This is a PR for MV3 support. The implementation is as I proposed [here.](https://github.com/webextension-toolbox/webextension-toolbox/issues/196#issuecomment-897729508)

- Update webpack-webextension-plugin version.
- Skip the manifest (v2) syntax validation --> opt-in / out at the cli level. Default is not to validate.
- Introduce the MV3 version of the book-it example.
- update README

Initially, this PR should be sufficient in supporting MV3. There might some small issues now and then. Anyway, the heavy lifting should already be gone after this PR is merged.

### CODE REVIEW

**Comment by here-nerd** [comment]
@tm1000 please review

**Comment by tm1000** [comment]
So the only thing is maybe we should have the example in a separate repo (or the yeoman example). I'm not sure. 

However we should add that directory to a `.npmignore` file so it doesn't get packaged. 

Either way this is great!

**Comment by here-nerd** [comment]
I will update .npmignore and also the polyfill section of README then.

**Comment by here-nerd** [comment]
Just noticed `.npmignore` already has `/examples`. I guess this is good enough.

**Comment by here-nerd** [comment]
@tm1000 this should be all. Please review again.

**Comment by tm1000** [comment]
Yes. I've been out of my office since Friday. I will be back tomorrow and merge this and fix the GitHub actions for publishing

**Review by tm1000 — APPROVED** [review]

**Pull request merged**
