### PR TITLE
Fix overwriting compiled manifest

### PR DESCRIPTION
**Pull request by vwheezy**
Fixes issue [628](https://github.com/webextension-toolbox/webpack-webextension-plugin/issues/628) in webpack-webextension-plugin

The CopyPlugin copies over the original `manifest.json`, overwriting the compiled version on all recompiles in dev/watch mode.

### CODE REVIEW

**Comment by vwheezy** [comment]
The patch I was given pushed to `compiledFiles` without changing the variable type. Commit 1844a05 fixes this

**Comment by tm1000** [comment]
@vwheezy the variable type should still be const. You can push to consts.

**Comment by vwheezy** [comment]
Oops. Sorry about that. I need some best practice tips here: should I just commit a fix or rewrite history?

**Comment by tm1000** [comment]
You can just commit again. I can squash and merge when it's all done

**Comment by vwheezy** [comment]
@tm1000 Committed!

**Pull request merged**
